# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.service import Service as ChromeService


class TestElectron:
    def setup_method(self, method):
        # driver_path = "D:/code/webdriver/116.0.5845/chromedriver.exe"
        driver_path = "D:/code/webdriver/80.0.3987.16/chromedriver.exe"
        service = ChromeService(executable_path=driver_path)
        options = webdriver.ChromeOptions()
        # options.binary_location = "D:/code/my-electron-app/out/my-electron-app-win32-x64/my-electron-app.exe"
        options.binary_location = "C:/Program Files (x86)/cqrcb-front-end-desktop/CqrcbFrontDesktop.exe"
        self.driver = webdriver.Chrome(options=options, service=service)
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_electron(self):
        self.driver.get("https://www.baidu.com/")
        self.driver.implicitly_wait(5)
        # self.driver.set_window_size(1936, 1048)
        # self.driver.maximize_window()
        self.driver.find_element(By.ID, "kw").click()
        self.driver.find_element(By.ID, "kw").send_keys("王皓宇")
        self.driver.find_element(By.ID, "su").click()
